name: Integration-test-with-terratest-for-Azure-Kubernetes

on:
  schedule:
    - cron: 0 17 * * *

jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 0.14.7
      DOCKER_REGISTRY_USERNAME: scalar-git
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.CR_PAT }}
      TERRATEST_ID: terratest-004
    defaults:
      run:
        working-directory: ./test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jre

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Install dependencies
        run: pipx inject ansible-core jmespath

      - name: Download scalardl client sdk
        run: |
          curl -L https://github.com/scalar-labs/scalardl-java-client-sdk/archive/v${SCALARDL_JAVA_CLIENT_SDK_VERSION}.tar.gz | tar xvzf -
          mv ./scalardl-java-client-sdk-${SCALARDL_JAVA_CLIENT_SDK_VERSION} ./scalardl-java-client-sdk
        env:
          SCALARDL_JAVA_CLIENT_SDK_VERSION: 2.1.0
        working-directory: ./test/src/integration

      - name: Set up GO
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.5
        id: go

      - name: Checkout scalar-terraform-examples
        uses: actions/checkout@v2
        with:
          repository: scalar-labs/scalar-terraform-examples
          ref: upgrade/k8s_version
          path: ./test/modules

      - name: Copy custom terraform.tfvars
        run: |
          paths=(network cassandra kubernetes)
          for d in "${paths[@]}"; do cp config/terraform/azure/${d}/terraform.tfvars ./modules/azure/${d}/; done
      - name: Create ssh key
        run: |
          ssh-keygen -N "" -t rsa -f test_key <<<y
          chmod 600 test_key
        working-directory: ./test/modules

      - name: Install terratest modules and run terratest
        run: |
          export GOPATH=$(pwd)
          export GOBIN=${GOPATH}/bin
          export PATH=${PATH}:${GOBIN}
          eval `ssh-agent`
          ssh-add ./modules/test_key
          mkdir -p ${GOBIN}
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          cd ${GITHUB_WORKSPACE}/test/src/modules && dep ensure
          cd ${GITHUB_WORKSPACE}/test/src/integration && dep ensure
          go test -run TestEndToEndK8s -timeout 120m -args -directory="../../modules/" -cloud_provider="azure"
      - name: Create jira issue
        if: failure()
        uses: ./.github/actions/create-jira-issue
        env:
          TEST_ENVIRONMENT: "Azure Kubernetes"
          JIRA_AUTH: ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE_DESCRIPTION: ${{ job.status }}
          JIRA_ASSIGNEE_ID: 60de5d7c285656006a977c3c # Milan

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: eng-notification
          SLACK_COLOR: danger
          SLACK_MESSAGE: ${{ job.status }}
          SLACK_TITLE: Integration test for Azure Kubernetes
          SLACK_USERNAME: github-actions[bot]
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Verification dashboard update failure status
        if: ${{ failure() }}
        uses: ./.github/actions/update-verification-dashboard
        env:
          TEST_ID: ${{ env.TERRATEST_ID }}
          TEST_STATUS: "false"
          TEST_ENVIRONMENT: "Azure Kubernetes"
          AUTOMATE_TOOL_TOKEN: ${{ secrets.AUTOMATE_TOOL_TOKEN }}
          
      - name: Verification dashboard update success status
        if: ${{ !failure() }}
        uses: ./.github/actions/update-verification-dashboard
        env:
          TEST_ID: ${{ env.TERRATEST_ID }}
          TEST_STATUS: "true"
          TEST_ENVIRONMENT: "Azure Kubernetes"
          AUTOMATE_TOOL_TOKEN: ${{ secrets.AUTOMATE_TOOL_TOKEN }}
