name: test-create-jira-issue

on:
  pull_request:
    branches:
      - master

jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest

    steps:
      - name: Create jira issue
        uses: ./.github/actions/create-jira-issue
        env:
          CLOUD_ENV: "Azure"
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE_DESCRIPTION: ${{ job.status }}
          JIRA_ASSIGNEE_ID: ${{ secrets.JIRA_USER_ID_TEI }}
